name: Deploy
on:
  push:
    branches:
      - main
jobs:
  call-test:
    uses: ./.github/workflows/test.yml
  deploy:
    needs: call-test
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@v1.4
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
