on: workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Build and run tests
        env:
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare
          bundle exec rails test:all
          bundle exec rspec
      - name: JS tests
        run: |
          yarn install
          yarn test
      - name: E2E tests
        run: |
          CYPRESS=1 bin/rails server -p 5017 &
          yarn cypress run
